### ISSUE TITLE
PG surveyor closes immediately after opening it

### ISSUE THREAD

**Issue by ghjjdsfg** [dlebansais/PgSurveyor-Disclosed#4]
Whenever I try to open PG surveyor, It opens, buffers, and then closes. How can I fix this?

**Comment by dlebansais** [comment]
I recently found a crash when the program is trying to reach github to check for updates. It should not matter for PgSurveyor because it makes sense to use it only when successfully connected to the Internet.
Nevertheless you can try to change the `CheckForUpdate` key in the registry at `HKEY_CURRENT_USER\SOFTWARE\Project Gorgon Tools\PgSurveyor`, set it to `False`. I can provide more info on how to do this if necessary.

**Comment by ghjjdsfg** [comment]
Yeah a little more info would be helpful, not sure where I'm supposed to do this.

**Comment by ghjjdsfg** [comment]
There was no CheckForUpdate key, I added one and set it to false. Same issue. Is there an error log I can check?

**Comment by dlebansais** [comment]
Looks like the program was never able to even reach the part where it writes down default settings. I'll see if I can add some logs, but currently there is nothing. Can you post more info about your system?

**Comment by ghjjdsfg** [comment]
Processor	Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz   3.50 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	21H1
NVIDIA GeForce GTX 1660 Ti
Hope this is what you meant

**Comment by dlebansais** [comment]
Thank. Yes, that's what I was looking for, in the hope I'd see something unusual.
I'm going to add logs. I'll keep you posted.

**Comment by dlebansais** [comment]
Try this, with the command line parameter `log`.
It should create a new file `log.txt` in the same folder (so don't do that in Program Files or any of its subfolders).
It might also fix your problem... But not work properly. The log might tell me why.
[PgSurveyor.zip](https://github.com/dlebansais/PgSurveyor-Disclosed/files/8619700/PgSurveyor.zip)

**Comment by ghjjdsfg** [comment]
The new log parameter worked
Here are the log contents;

5/5/2022 1:15:43 AM - Command line arguments parsed
5/5/2022 1:15:44 AM - MainWindow initializing
5/5/2022 1:15:44 AM - MainWindow initialized
5/5/2022 1:15:44 AM - Reading settings in file
5/5/2022 1:15:44 AM - Loading icons
5/5/2022 1:15:44 AM - Initializing update check
5/5/2022 1:15:44 AM - Zone set: Eltibule
5/5/2022 1:15:44 AM - LocationList set: 5
5/5/2022 1:15:44 AM - MainWindow loaded
5/5/2022 1:15:44 AM - Reading registry settings
5/5/2022 1:15:44 AM - Calculating screen bounds
5/5/2022 1:15:44 AM - 1920 x 1200
5/5/2022 1:15:44 AM - Resetting corners
5/5/2022 1:15:44 AM - Moving map window
5/5/2022 1:15:44 AM - Moving inventory window
5/5/2022 1:15:44 AM - Starting chat parser
5/5/2022 1:15:44 AM - MainWindow loading complete
5/5/2022 1:15:44 AM - Unhandled Exception
5/5/2022 1:15:44 AM - Exception has been thrown by the target of an invocation.
5/5/2022 1:15:44 AM -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ghjjdsfg** [comment]
From windows event logs;

Application: PgSurveyor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemWatcher.set_Path(System.String)
   at PgChatParser.Parser.TryConnecting()
   at PgChatParser.Parser.OnChatTimer()

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at PgSurveyor.App.Main()

Next;

Faulting application name: PgSurveyor.exe, version: 1.1.2.782, time stamp: 0xccf9ce38
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1645, time stamp: 0x630193b4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x1cd4
Faulting application start time: 0x01d8601da486c0a5
Faulting application path: C:\Users\Ryder\Desktop\PgSurveyor\PgSurveyor.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: f38b509b-7a0d-4934-b111-708fbe9d3ff3
Faulting package full name: 
Faulting package-relative application ID: 

Next (informational);

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: PgSurveyor.exe
P2: 1.1.2.782
P3: ccf9ce38
P4: System
P5: 4.8.4488.0
P6: 61e76f72
P7: 2667
P8: 7b
P9: System.ArgumentException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_PgSurveyor.exe_65a86ccf303c1a15a8be5ff58352c925db317bc0_a57f7038_f875f0c6-b4d1-4731-afd7-a3ed557b2434

Analysis symbol: 
Rechecking for solution: 0
Report Id: f38b509b-7a0d-4934-b111-708fbe9d3ff3
Report Status: 4
Hashed bucket: 
Cab Guid: 0

next (informational);

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: PgSurveyor.exe
P2: 1.1.2.782
P3: ccf9ce38
P4: System
P5: 4.8.4488.0
P6: 61e76f72
P7: 2667
P8: 7b
P9: System.ArgumentException
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_PgSurveyor.exe_65a86ccf303c1a15a8be5ff58352c925db317bc0_a57f7038_f875f0c6-b4d1-4731-afd7-a3ed557b2434

Analysis symbol: 
Rechecking for solution: 0
Report Id: f38b509b-7a0d-4934-b111-708fbe9d3ff3
Report Status: 4
Hashed bucket: 
Cab Guid: 0

**Comment by dlebansais** [comment]
Thank for the logs. It doesn't help me much but at least I have eliminated some possibilities.
I've made a new version you can try again. Beside more logs, this one writes down settings in the registry, so you can disable update there if needed
[PgSurveyor.zip](https://github.com/dlebansais/PgSurveyor-Disclosed/files/8629637/PgSurveyor.zip)
.

**Comment by ghjjdsfg** [comment]
Turns out I'm bad at reading and just had to turn on chat logs.
